server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple-instances
          uri: https://github.com/jhimy-java/microservicios-project
          search-paths: config-data
  application:
    name: config-server
